version: '3.8'

services:
  telegram_bot_prod:
    build: ./
    container_name: telegram_bot_prod
    env_file:
      - .env.prod
    volumes:
      - telegram_bot_prod_db:/app/data
    restart: unless-stopped

volumes:
  telegram_bot_prod_db:

