version: '3.8'

services:
  telegram_bot_test:
    build: ./
    container_name: telegram_bot_test
    env_file:
      - .env.test
    volumes:
      - telegram_bot_test_db:/app/data
    restart: unless-stopped
    network_mode: "host"  # Для доступа к localhost:8089

volumes:
  telegram_bot_test_db:

